services: 
  relayer:
    image: us-central1-docker.pkg.dev/oxbow-406621/privacy-pools-core/staging/relayer
    serviceAccount: relayer-staging
    command: python3
    args: ["/app/main.py"]
    resources:
      cpu: 100m
      memory: 2Gi
    
    service:
      type: ClusterIP
      port: 80
      protocol: TCP
      targetPort: 3000

    ingress:
      host: testnet-relayer.privacypools.com
      paths:
      - /
      tls:
        - secretName: privacypools-tls
          hosts:
            - testnet-relayer.privacypools.com
