[book]
title = "Privacy Pool Documentation"
description = "Private onchain money transfers"
authors = ["Wonderland"]
language = "en"
multilingual = false
src = "src"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.katex]
after = ["links"]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
git-repository-url = "https://github.com/defi-wonderland/privacy-pool-core"
