services:
  relayer:
    network_mode: host
    user: 1000:1000
    build:
      context: ../../
      dockerfile: packages/relayer/Dockerfile
    volumes:
      - /tmp/pp_relayer.sqlite:/pp_relayer.sqlite
      - ./config.example.json:/build/packages/relayer/config.json
      - ../circuits/artifacts:/build/node_modules/@privacy-pool-core/sdk/dist/node/artifacts
    ports:
      - "3000:3000" # HOST:CONTAINER
