name: SDK / Canary Release

on: workflow_dispatch

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

defaults:
  run:
    working-directory: packages/sdk

jobs:
  canary-release:
    name: SDK Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out github repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "yarn"
          registry-url: 'https://registry.npmjs.org'
          token: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: yarn --frozen-lockfile --network-concurrency 1

      - name: Build SDK
        run: |
          yarn build
          chmod +x ./scripts/copy_circuits.sh
          bash ./scripts/copy_circuits.sh
        working-directory: packages/sdk

      - name: Set canary version
        run: yarn version --new-version "0.0.0-${GITHUB_SHA::8}" --no-git-tag-version

      - name: Publish canary
        # run: npm publish --access public --tag canary
        run: npm publish --access restricted --tag canary