name: SDK

on:
  pull_request:
    paths:
      - "packages/sdk/**"
      - ".github/workflows/**"
  push:
    branches: [main, dev]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

defaults:
  run:
    working-directory: packages/sdk

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out github repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup .npmrc file
        run: |
          echo "@defi-wonderland:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PKG_REGISTRY_TOKEN }}" >> .npmrc

      - name: Install dependencies
        run: yarn --frozen-lockfile --network-concurrency 1

      - name: Run Build
        run: yarn build

      - name: Check types
        run: yarn check-types

  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out github repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup .npmrc file
        run: |
          echo "@defi-wonderland:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PKG_REGISTRY_TOKEN }}" >> .npmrc

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests with coverage
        run: yarn test:cov
